---
- name: Download Element archive
  get_url:
    url: "{{ element_web_archive_url }}"
    dest: "{{ global_cache_dir }}/element-{{ element_web_checksum.split(':')[-1][:40] }}.tar.gz"
    checksum: "{{ element_web_checksum }}"
  become: False
  delegate_to: localhost

- name: Clear unarchive target directory
  file:
    path: /opt/element-web-versions/{{ element_web_checksum.split(':')[-1][:40] }}
    state: absent

- name: Create unarchive target directory
  file:
    path: /opt/element-web-versions/{{ element_web_checksum.split(':')[-1][:40] }}
    state: directory

- name: Unpack Element archive
  unarchive:
    src: "{{ global_cache_dir }}/element-{{ element_web_checksum.split(':')[-1][:40] }}.tar.gz"
    dest: /opt/element-web-versions/{{ element_web_checksum.split(':')[-1][:40] }}

- name: Get base name of the Element path
  find:
    paths: /opt/element-web-versions/{{ element_web_checksum.split(':')[-1][:40] }}
    file_type: directory
  register: _element_web_base_name

- name: Set the symlink to the installed Element version
  file:
    src: "{{ _element_web_base_name.files[0].path }}"
    dest: /tmp/element-symlink
    state: link

# mv is atomic and we want the activation of the new version to be atomic
- name: Move the symlink into its place
  command: mv -Tf /tmp/element-symlink /opt/element-web
