---
- name: Retrieve Element symlink target
  stat:
    path: /opt/element-web
  register: _element_web_symlink_stat

- include_tasks: install.yml
  when: element_web_checksum.split(':')[-1][:40] not in (_element_web_symlink_stat.stat.lnk_target | default(""))

- name: Set Element config
  copy:
    content: "{{ element_web_config | to_nice_json }}\n"
    dest: "{{ element_web_write_config_to_path }}"
